server:
  servlet:
    context-path: /dev/bot/ozon/helper
  port: 1212

logging:
  level:
    ru.asteises.ozonhelper: DEBUG
    org.telegram: INFO
  file:
    name: /app/logs/app.log

management:
  server:
    base-path: /
  endpoints:
    web:
      exposure:
        include: health,info

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
  miniapp:
    url: https://asteises.ru/dev/bot/ozon/helper

ozon:
  api:
    url: https://api-seller.ozon.ru

encryption:
  password: ${ENCRYPT_PASSWORD}
  salt: ${ENCRYPT_SALT}
spring:
  application:
    name: ozon-helper
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  main:
    banner-mode: log
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ozon-helper-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
