server:
  port: 1212

logging:
  level:
    ru.asteises.ozonhelper.config.telegram: DEBUG
    org.telegram: INFO

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

spring:
  application:
    name: ozon-helper
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ozon-helper-db}
    username: ${OZON_HELPER_DB_USER:postgres}
    password: ${OZON_HELPER_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect