server:
  port: 1212

logging:
  level:
    ru.asteises.ozonhelper: DEBUG
    org.telegram: INFO

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
  miniapp:
    url: https://yandex.ru

ozon:
  api:
    url: https://api-seller.ozon.ru

spring:
  application:
    name: ozon-helper
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  main:
    banner-mode: log
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ozon-helper-db}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect